created ExploreFragment and it's logic part.
CSwala/CSwala-android pull request #110
Opened 2021-03-21 12:32 UTC by ayushman999

## Explanation

This PR completes the explore fragment logic part that is #99  and fetches data from the firestore and shows it in a different activity.
## Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] The PR explanation includes the words "Fixes #bugnum: ..." (or "Fixes part of #bugnum" if the PR only partially fixes an issue).
- [x ] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x ] The PR does not break any part of the existing code.
- [x ] The PR creator have carefully read & adher to the contributing guidelines of the project.
- [x ] The PR is made to the branch that's **called** "develop".
- [x ] The PR is made from a branch that is up-to-date with "develop".
- [ ] The PR's branch is based on "main" and not on any other branch.

2021-03-21 16:13 UTC, riturajjain2000 commented on app/src/main/java/com/cswala/cswala/Fragments/ExploreFragment.java
> +    public void onItemClicked(String item) {
Add this intent to intent helper class

2021-03-21 16:17 UTC, riturajjain2000 requested changes
- Remove the 'EXPLORE ' text from the top of the fragment
- The search bar is not visible , add a  background 
- add a small secondary text in the list items in the upper right corner , which will show the 'tag' string from the DB

Rest LGTM!

2021-03-21 16:17 UTC, riturajjain2000 commented on app/src/main/java/com/cswala/cswala/Fragments/ExploreFragment.java
> +        Intent transfer=new Intent(getContext(), TechDataActivity.class);
Add this intent to intent helper class

2021-03-21 17:51 UTC, ayushman999 commented on app/src/main/java/com/cswala/cswala/Fragments/ExploreFragment.java
> +        Intent transfer=new Intent(getContext(), TechDataActivity.class);
Sure

2021-03-21 18:25 UTC, ayushman999 commented
Did all the required changes, please go through it.

2021-03-22 05:39 UTC, riturajjain2000 requested changes
- make the search icon, placeholder text and, close icon color dark, as white on yellow is not visible, also see if you can make the placeholder 'search...' to match the same font as the other texts in the app i.e to `press start 2p`
- You added the `tag` in the tech data activity , you have to add that in the list items in the explore fragment 
<img width="540" alt="Screenshot_1616391361" src="https://user-images.githubusercontent.com/48384309/111944959-c4063700-8afe-11eb-8b20-9b22e6e99328.png">

like this in the upper right corner 

- The app is crashing now , some problem in the Animation of login class because of missing handlers for thread , so fix that in this PR only and raise a issue for same so as you can get points

2021-03-22 05:42 UTC, riturajjain2000 commented
### LOGCAT -
`android.util.AndroidRuntimeException: Animators may only be run on Looper threads
            at android.animation.ValueAnimator.cancel(ValueAnimator.java:1104)
            at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:956)
            at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:912)
            at android.view.ViewPropertyAnimator.alpha(ViewPropertyAnimator.java:729)
            at com.cswala.cswala.Activities.LoginActivity$6.run(LoginActivity.java:218)
            at java.util.TimerThread.mainLoop(Timer.java:562)
            at java.util.TimerThread.run(Timer.java:512)`

2021-03-23 15:02 UTC, riturajjain2000 approved these changes

2021-03-23 15:03 UTC, merged